# Generated by Django 4.1.4 on 2024-07-24 05:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 7, 24, 12, 51, 58, 353655)),
        ),
        migrations.CreateModel(
            name='CacheValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('Jumlah', models.FloatField()),
                ('Harga', models.FloatField()),
                ('KodeProduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.produk')),
            ],
        ),
    ]
