# Generated by Django 4.0.4 on 2024-03-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konversimaster',
            name='IDKodeKonversiMaster',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
