# Generated by Django 4.0.4 on 2024-03-10 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsppb',
            name='NoSPK',
        ),
        migrations.AddField(
            model_name='detailsppb',
            name='DetailSPK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='abadi.detailspk'),
        ),
    ]
