# Generated by Django 4.1.2 on 2024-03-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='kategori',
        ),
    ]
