# Generated by Django 4.1.4 on 2024-07-24 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0002_alter_produk_tanggalpembuatan_cachevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachevalue',
            name='Harga',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cachevalue',
            name='Jumlah',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 7, 24, 12, 52, 16, 913697)),
        ),
    ]
