# Generated by Django 4.0.4 on 2024-03-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0002_alter_konversimaster_idkodekonversimaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailkonversiproduksi',
            name='IDDetailKonversiProduksi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detailspk',
            name='IDDetailSPK',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detailsppb',
            name='IDDetailSPPB',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detailsuratjalanpembelian',
            name='IDDetailSJPembelian',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lokasi',
            name='IDLokasi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='penyesuaian',
            name='IDPenyesuaian',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='penyusun',
            name='IDKodePenyusun',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saldoawalartikel',
            name='IDSaldoAwalBahanBaku',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saldoawalbahanbaku',
            name='IDSaldoAwalBahanBaku',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaksigudang',
            name='IDDetailTransaksiGudang',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaksiproduksi',
            name='idTransaksiProduksi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
