# Generated by Django 4.1.2 on 2024-03-02 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0003_alter_penyusun_lokasi_alter_transaksigudang_lokasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldoawalartikel',
            name='Harga',
        ),
    ]
