# Generated by Django 4.1.2 on 2024-03-17 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0003_alter_detailkonversiproduksi_kodepenyesuaian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.date(2024, 3, 17)),
        ),
    ]
