# Generated by Django 4.1.2 on 2024-03-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0004_produk_tanggalpembuatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(auto_now_add=True),
        ),
    ]
