# Generated by Django 4.1.4 on 2024-08-02 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0004_alter_produk_tanggalpembuatan_transaksicat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 2, 7, 24, 35, 709185)),
        ),
    ]
