# Generated by Django 4.1.2 on 2024-03-17 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0005_alter_produk_tanggalpembuatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdukSubkon',
            fields=[
                ('IDProdukSubkon', models.AutoField(primary_key=True, serialize=False)),
                ('NamaProduk', models.CharField(max_length=255)),
                ('Unit', models.CharField(max_length=20)),
                ('KodeArtikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.artikel')),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiSubkon',
            fields=[
                ('IDTransaksiSubkon', models.AutoField(primary_key=True, serialize=False)),
                ('Tanggal', models.DateField()),
                ('Jumlah', models.IntegerField()),
                ('IDProdukSubkon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.produksubkon')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoAwalSubkon',
            fields=[
                ('IDSaldoAwalProdukSubkon', models.AutoField(primary_key=True, serialize=False)),
                ('Jumlah', models.IntegerField()),
                ('Tanggal', models.DateField()),
                ('IDProdukSubkon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.produksubkon')),
            ],
        ),
        migrations.CreateModel(
            name='PemusnahanBahanBaku',
            fields=[
                ('IDPemusnahanBahanBaku', models.AutoField(primary_key=True, serialize=False)),
                ('Tanggal', models.DateField()),
                ('Jumlah', models.IntegerField()),
                ('KodeBahanBaku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.produk')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.lokasi')),
            ],
        ),
        migrations.CreateModel(
            name='PemusnahanArtikel',
            fields=[
                ('IDPemusnahanArtikel', models.AutoField(primary_key=True, serialize=False)),
                ('Tanggal', models.DateField()),
                ('Jumlah', models.IntegerField()),
                ('KodeArtikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.artikel')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.lokasi')),
            ],
        ),
    ]
