# Generated by Django 4.1.4 on 2024-08-07 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0006_saldoawalbahanbaku_sisapengambilan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 7, 8, 13, 51, 65952)),
        ),
        migrations.AlterField(
            model_name='saldoawalbahanbaku',
            name='Jumlah',
            field=models.FloatField(),
        ),
    ]
