# Generated by Django 4.1.2 on 2024-03-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0006_produksubkon_transaksisubkon_saldoawalsubkon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldoawalartikel',
            old_name='IDBahanBaku',
            new_name='IDArtikel',
        ),
    ]
