# Generated by Django 4.1.2 on 2024-03-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0007_rename_idbahanbaku_saldoawalartikel_idartikel'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldoawalartikel',
            name='Tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saldoawalbahanbaku',
            name='Tanggal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
