# Generated by Django 4.1.4 on 2024-08-07 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0007_alter_produk_tanggalpembuatan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoAwalProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saldo', models.FloatField()),
                ('tahun', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 7, 20, 7, 59, 202407)),
        ),
    ]
