# Generated by Django 4.1.2 on 2024-03-18 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0008_saldoawalartikel_tanggal_saldoawalbahanbaku_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksigudang',
            name='DetailSPK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.detailspk'),
        ),
        migrations.AddField(
            model_name='transaksiproduksi',
            name='DetailSPK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.detailspk'),
        ),
    ]
