# Generated by Django 4.1.4 on 2024-08-08 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0009_rename_tahun_saldoawalproduksi_tanggal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 8, 13, 50, 42, 156258)),
        ),
        migrations.AlterField(
            model_name='transaksigudang',
            name='jumlah',
            field=models.FloatField(),
        ),
    ]
