# Generated by Django 4.1.2 on 2024-03-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0009_transaksigudang_detailspk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='Jumlahminimal',
            field=models.IntegerField(default=0),
        ),
    ]
