# Generated by Django 4.1.2 on 2024-03-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0010_produk_jumlahminimal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldoawalartikel',
            old_name='IDSaldoAwalBahanBaku',
            new_name='IDSaldoawalArtikel',
        ),
        migrations.AlterField(
            model_name='saldoawalbahanbaku',
            name='Jumlah',
            field=models.FloatField(),
        ),
    ]
