# Generated by Django 4.1.4 on 2024-08-12 01:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0011_alter_detailsuratjalanpembelian_jumlah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyesuaian',
            name='konversi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 12, 8, 7, 40, 490052)),
        ),
        migrations.CreateModel(
            name='HargaArtikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('Harga', models.FloatField()),
                ('KodeArtikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.artikel')),
            ],
        ),
    ]
