# Generated by Django 4.1.2 on 2024-03-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0012_alter_produk_tanggalpembuatan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldoawalartikel',
            old_name='IDSaldoawalArtikel',
            new_name='IDSaldoAwalBahanBaku',
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saldoawalbahanbaku',
            name='Jumlah',
            field=models.IntegerField(),
        ),
    ]
