# Generated by Django 4.1.4 on 2024-08-14 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0012_alter_penyesuaian_konversi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 14, 16, 12, 56, 956705)),
        ),
        migrations.CreateModel(
            name='PenyesuaianArtikel',
            fields=[
                ('IDPenyesuaian', models.AutoField(primary_key=True, serialize=False)),
                ('TanggalMulai', models.DateField()),
                ('TanggalMinus', models.DateField(blank=True, null=True)),
                ('konversi', models.FloatField()),
                ('KodeArtikel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.artikel')),
                ('lokasi', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abadi.lokasi')),
            ],
        ),
    ]
