# Generated by Django 4.1.2 on 2024-03-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0013_rename_idsaldoawalartikel_saldoawalartikel_idsaldoawalbahanbaku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spk',
            name='NomorPO',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
