# Generated by Django 4.1.4 on 2024-08-22 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0013_alter_produk_tanggalpembuatan_penyesuaianartikel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksigudang',
            name='keteranganACCPurchasing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 22, 13, 10, 9, 604469)),
        ),
    ]
