# Generated by Django 4.1.4 on 2024-08-22 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0014_transaksigudang_keteranganaccpurchasing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksigudang',
            old_name='keteranganACCPurchasing',
            new_name='KeteranganACCPurchasing',
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 22, 13, 41, 0, 846763)),
        ),
    ]
