# Generated by Django 4.1.2 on 2024-03-20 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0015_remove_spk_nomorpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksigudang',
            name='DetailSPK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.detailspk'),
        ),
    ]
