# Generated by Django 4.1.4 on 2024-08-22 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0015_rename_keteranganaccpurchasing_transaksigudang_keteranganaccpurchasing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 22, 14, 19, 34, 376380)),
        ),
        migrations.AlterField(
            model_name='transaksigudang',
            name='KeteranganACCPurchasing',
            field=models.BooleanField(),
        ),
    ]
