# Generated by Django 4.1.4 on 2024-08-22 22:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0016_alter_produk_tanggalpembuatan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodePO', models.CharField(max_length=100, unique=True)),
                ('Tanggal', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 23, 5, 27, 50, 977099)),
        ),
        migrations.CreateModel(
            name='DetailPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField()),
                ('KodePO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.purchaseorder')),
                ('KodeProduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.produk')),
            ],
        ),
    ]
