# Generated by Django 4.1.2 on 2024-03-25 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0016_alter_transaksigudang_detailspk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksiproduksi',
            name='DetailSPK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.detailspk'),
        ),
    ]
