# Generated by Django 4.1.4 on 2024-08-22 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0018_rename_status_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 23, 5, 55, 51, 49540)),
        ),
    ]
