# Generated by Django 4.1.4 on 2024-08-22 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0019_alter_produk_tanggalpembuatan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailpo',
            old_name='jumlah',
            new_name='Jumlah',
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 23, 5, 56, 1, 45458)),
        ),
    ]
