# Generated by Django 4.1.4 on 2024-04-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0019_penyusun_versi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailKonversiProduksi',
        ),
    ]
