# Generated by Django 4.1.4 on 2024-08-26 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0020_rename_jumlah_detailpo_jumlah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsuratjalanpembelian',
            name='PPN',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detailsuratjalanpenerimaanproduksubkon',
            name='Potongan',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 26, 18, 45, 28, 107168)),
        ),
    ]
