# Generated by Django 4.1.4 on 2024-04-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0020_delete_detailkonversiproduksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyesuaian',
            name='konversi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
