# Generated by Django 4.1.4 on 2024-08-27 02:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0021_detailsuratjalanpembelian_ppn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratjalanpembelian',
            name='PO',
        ),
        migrations.AddField(
            model_name='detailsuratjalanpembelian',
            name='PO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abadi.detailpo'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 27, 9, 38, 2, 76142)),
        ),
    ]
