# Generated by Django 4.1.4 on 2024-08-27 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0022_remove_suratjalanpembelian_po_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 27, 9, 38, 46, 396446)),
        ),
    ]
