# Generated by Django 4.1.4 on 2024-05-06 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0023_confirmationorder_detailconfirmationorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubkonKirim',
            fields=[
                ('IDSubkonKirim', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Tanggal', models.DateField()),
                ('supplier', models.CharField(max_length=255)),
                ('PO', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetailSubkonKirim',
            fields=[
                ('IDDetailSubkonKirim', models.AutoField(primary_key=True, serialize=False)),
                ('Jumlah', models.IntegerField()),
                ('KeteranganACC', models.BooleanField()),
                ('Harga', models.FloatField()),
                ('IDSubkonKirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.subkonkirim')),
                ('KodeProduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.produk')),
            ],
        ),
    ]
