# Generated by Django 4.1.4 on 2024-08-29 03:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0023_alter_produk_tanggalpembuatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 29, 10, 50, 18, 207210)),
        ),
        migrations.CreateModel(
            name='PemusnahanProdukSubkon',
            fields=[
                ('IDPemusnahanArtikel', models.AutoField(primary_key=True, serialize=False)),
                ('Tanggal', models.DateField()),
                ('Jumlah', models.IntegerField()),
                ('Keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('KodeProdukSubkon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.produksubkon')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.lokasi')),
            ],
        ),
        migrations.CreateModel(
            name='PemusnahanBahanBakuSubkon',
            fields=[
                ('IDPemusnahanBahanBaku', models.AutoField(primary_key=True, serialize=False)),
                ('Tanggal', models.DateField()),
                ('Jumlah', models.FloatField()),
                ('Keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('KodeBahanBaku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.bahanbakusubkon')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.lokasi')),
            ],
        ),
    ]
