# Generated by Django 4.1.4 on 2024-05-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0024_subkonkirim_detailsubkonkirim'),
    ]

    operations = [
        migrations.AddField(
            model_name='spk',
            name='StatusAktif',
            field=models.BooleanField(default=True),
        ),
    ]
