# Generated by Django 4.1.4 on 2024-08-29 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0024_alter_produk_tanggalpembuatan_pemusnahanproduksubkon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsuratjalanpembelian',
            name='hargappn',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 8, 29, 13, 31, 52, 105553)),
        ),
    ]
