# Generated by Django 4.1.4 on 2024-05-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0025_spk_statusaktif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='keterangan',
        ),
        migrations.AddField(
            model_name='produk',
            name='keteranganGudang',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='keteranganProduksi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='keteranganPurchasing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='keteranganRND',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
