# Generated by Django 4.1.4 on 2024-05-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0026_remove_produk_keterangan_produk_keterangangudang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationorder',
            name='StatusAktif',
            field=models.BooleanField(default=True),
        ),
    ]
