# Generated by Django 5.1 on 2024-09-02 02:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0026_detailsuratjalanpenerimaanproduksubkon_hargapotongan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemusnahanartikel',
            name='ismutasi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 2, 9, 21, 1, 402577)),
        ),
        migrations.CreateModel(
            name='Stokadjustmenproduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('Jumlah', models.FloatField()),
                ('Keterangan', models.TextField()),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('KodeProduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.produk')),
            ],
        ),
        migrations.CreateModel(
            name='Versi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Versi', models.CharField(max_length=50)),
                ('Tanggal', models.DateField()),
                ('keterangan', models.TextField()),
                ('KodeArtikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.artikel')),
            ],
        ),
    ]
