# Generated by Django 4.1.4 on 2024-05-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0027_confirmationorder_statusaktif'),
    ]

    operations = [
        migrations.CreateModel(
            name='BahanBakuSubkon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodeProduk', models.CharField(max_length=20)),
                ('NamaProduk', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='spk',
            name='StatusDisplay',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='spk',
            name='StatusAktif',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
