# Generated by Django 5.1 on 2024-09-02 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0027_pemusnahanartikel_ismutasi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemusnahanartikel',
            name='ismutasi',
        ),
        migrations.AddField(
            model_name='pemusnahanbahanbaku',
            name='ismutasi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 2, 9, 23, 42, 246774)),
        ),
    ]
