# Generated by Django 4.1.4 on 2024-05-08 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0028_bahanbakusubkon_spk_statusdisplay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsppb',
            name='IDCO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.confirmationorder'),
        ),
    ]
