# Generated by Django 5.1 on 2024-09-02 02:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0028_remove_pemusnahanartikel_ismutasi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemusnahanbahanbaku',
            name='ismutasi',
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 2, 9, 33, 50, 209408)),
        ),
        migrations.CreateModel(
            name='transaksimutasikodestok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jumlah', models.FloatField()),
                ('Keterangan', models.TextField()),
                ('Tanggal', models.DateField()),
                ('KodeProdukAsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutasi_produk_asal', to='abadi.produk')),
                ('kodeProdukTujuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutasi_produk_tujuan', to='abadi.produk')),
            ],
        ),
    ]
