# Generated by Django 4.1.4 on 2024-05-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0029_detailsppb_idco'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyusun',
            name='keterangan',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='detailsppb',
            name='IDCO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abadi.confirmationorder'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='keteranganGudang',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='keteranganProduksi',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='keteranganPurchasing',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='keteranganRND',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
