# Generated by Django 4.1.4 on 2024-09-02 03:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0029_remove_pemusnahanbahanbaku_ismutasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksimutasikodestok',
            name='Lokasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.lokasi'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 2, 10, 10, 32, 69492)),
        ),
    ]
