# Generated by Django 4.1.4 on 2024-09-02 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0030_transaksimutasikodestok_lokasi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksimutasikodestok',
            old_name='kodeProdukTujuan',
            new_name='KodeProdukTujuan',
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 2, 18, 15, 42, 217163)),
        ),
    ]
