# Generated by Django 4.1.4 on 2024-05-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0030_penyusun_keterangan_alter_detailsppb_idco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodeDisplay', models.CharField(max_length=20)),
                ('keterangan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetailSPKDisplay',
            fields=[
                ('IDDetailSPK', models.AutoField(primary_key=True, serialize=False)),
                ('Jumlah', models.IntegerField()),
                ('KodeArtikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.display')),
                ('NoSPK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.spk')),
            ],
        ),
    ]
