# Generated by Django 4.1.4 on 2024-05-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0031_display_detailspkdisplay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailspkdisplay',
            old_name='KodeArtikel',
            new_name='KodeDisplay',
        ),
    ]
