# Generated by Django 4.1.4 on 2024-09-03 01:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0031_rename_kodeproduktujuan_transaksimutasikodestok_kodeproduktujuan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyusun',
            name='KodeVersi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.versi'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 3, 8, 19, 58, 777096)),
        ),
    ]
