# Generated by Django 4.1.4 on 2024-09-03 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0032_penyusun_kodeversi_alter_produk_tanggalpembuatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 3, 8, 48, 53, 295994)),
        ),
        migrations.AlterField(
            model_name='versi',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
