# Generated by Django 4.1.4 on 2024-05-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0033_suratjalanpenerimaanproduksubkon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksibahanbakusubkon',
            old_name='IDKodeBahanBaku',
            new_name='KodeBahanBaku',
        ),
        migrations.RenameField(
            model_name='transaksisubkon',
            old_name='IDProdukSubkon',
            new_name='KodeProduk',
        ),
        migrations.RemoveField(
            model_name='detailsuratjalanpenerimaanproduksubkon',
            name='KodeDisplay',
        ),
        migrations.RemoveField(
            model_name='detailsuratjalanpengirimanbahanbakusubkon',
            name='KodeDisplay',
        ),
        migrations.AddField(
            model_name='detailsuratjalanpenerimaanproduksubkon',
            name='KodeProduk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.produksubkon'),
        ),
        migrations.AddField(
            model_name='detailsuratjalanpengirimanbahanbakusubkon',
            name='KodeBahanBaku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.bahanbakusubkon'),
        ),
    ]
