# Generated by Django 4.1.4 on 2024-05-11 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0034_rename_idkodebahanbaku_transaksibahanbakusubkon_kodebahanbaku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsppb',
            name='DetailSPKDisplay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.detailspkdisplay'),
        ),
        migrations.AlterField(
            model_name='detailsppb',
            name='DetailSPK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.detailspk'),
        ),
    ]
