# Generated by Django 4.1.4 on 2024-05-11 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0035_detailsppb_detailspkdisplay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksiproduksi',
            name='DetailSPKDisplay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.detailspkdisplay'),
        ),
    ]
