# Generated by Django 4.1.4 on 2024-09-03 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0035_penyusun_allowance_penyusun_kuantitas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyusun',
            name='keterangan',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 3, 10, 18, 50, 258899)),
        ),
    ]
