# Generated by Django 4.1.4 on 2024-05-11 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0036_transaksiproduksi_detailspkdisplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksiproduksi',
            name='KodeArtikel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.artikel'),
        ),
    ]
