# Generated by Django 4.1.4 on 2024-05-12 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0038_remove_transaksiproduksi_detailspkdisplay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksigudang',
            name='DetailSPKDisplay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.detailspkdisplay'),
        ),
    ]
