# Generated by Django 4.1.4 on 2024-09-04 02:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0038_remove_penyusun_versi_alter_produk_tanggalpembuatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksiproduksi',
            name='VersiArtikel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.versi'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 4, 9, 5, 3, 743689)),
        ),
    ]
