# Generated by Django 4.1.4 on 2024-05-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0040_remove_penyesuaian_tanggalakhir'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyesuaian',
            name='TanggalMinus',
            field=models.DateField(blank=True, null=True),
        ),
    ]
