# Generated by Django 4.1.4 on 2024-09-05 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0040_pemusnahanartikel_versiartikel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='versi',
            name='isdefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 5, 9, 42, 4, 796569)),
        ),
    ]
