# Generated by Django 4.1.4 on 2024-05-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0041_penyesuaian_tanggalminus'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksibahanbakusubkon',
            name='Jumlah',
            field=models.IntegerField(default=0),
        ),
    ]
