# Generated by Django 4.1.4 on 2024-09-05 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0041_versi_isdefault_alter_produk_tanggalpembuatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 5, 13, 2, 9, 864282)),
        ),
        migrations.DeleteModel(
            name='KonversiMaster',
        ),
    ]
