# Generated by Django 4.1.4 on 2024-05-18 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0042_transaksibahanbakusubkon_jumlah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsuratjalanpenerimaanproduksubkon',
            name='NoSuratJalan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.suratjalanpenerimaanproduksubkon'),
        ),
    ]
