# Generated by Django 4.1.4 on 2024-09-12 09:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0042_alter_produk_tanggalpembuatan_delete_konversimaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsppb',
            name='VersiArtikel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.versi'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 16, 0, 6, 434295)),
        ),
    ]
