# Generated by Django 4.1.4 on 2024-09-12 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0043_detailsppb_versiartikel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksisubkon',
            name='Keterangan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 13, 5, 7, 13, 961924)),
        ),
    ]
