# Generated by Django 4.1.4 on 2024-05-18 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0043_alter_detailsuratjalanpenerimaanproduksubkon_nosuratjalan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoAwalBahanBakuSubkon',
            fields=[
                ('IDSaldoAwalBahanBakuSubkon', models.AutoField(primary_key=True, serialize=False)),
                ('Jumlah', models.IntegerField()),
                ('Tanggal', models.DateField()),
                ('IDBahanBakuSubkon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.bahanbakusubkon')),
            ],
        ),
    ]
