# Generated by Django 4.1.4 on 2024-06-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0044_saldoawalbahanbakusubkon'),
    ]

    operations = [
        migrations.AddField(
            model_name='konversimaster',
            name='Allowance',
            field=models.FloatField(default=0),
        ),
    ]
