# Generated by Django 4.1.4 on 2024-06-05 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0045_konversimaster_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailconfirmationorder',
            name='Display',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.display'),
        ),
        migrations.AlterField(
            model_name='detailconfirmationorder',
            name='Artikel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.artikel'),
        ),
    ]
