# Generated by Django 5.0.3 on 2024-06-12 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0045_konversimaster_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsppb',
            name='DetailBahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.produk'),
        ),
        migrations.AlterField(
            model_name='pemusnahanbahanbaku',
            name='Jumlah',
            field=models.FloatField(),
        ),
    ]
