# Generated by Django 4.1.4 on 2024-06-14 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0046_detailconfirmationorder_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsppb',
            name='DetailBahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.produk'),
        ),
    ]
