# Generated by Django 4.1.4 on 2024-09-23 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0047_alter_produk_tanggalpembuatan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratJalanPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoSuratJalan', models.CharField(max_length=255, unique=True)),
                ('Tanggal', models.DateField()),
                ('supplier', models.CharField(max_length=255)),
                ('NoInvoice', models.CharField(blank=True, max_length=255, null=True)),
                ('TanggalInvoice', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 23, 21, 39, 47, 482141)),
        ),
        migrations.CreateModel(
            name='DetailSuratJalanPembelian',
            fields=[
                ('IDDetailSJPembelian', models.AutoField(primary_key=True, serialize=False)),
                ('Jumlah', models.FloatField()),
                ('KeteranganACC', models.BooleanField()),
                ('Harga', models.FloatField()),
                ('HargaDollar', models.FloatField(default=0)),
                ('PPN', models.BooleanField(default=True)),
                ('hargappn', models.FloatField(default=0)),
                ('KodeProduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.produk')),
                ('NoSuratJalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.suratjalanpembelian')),
                ('PO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abadi.detailpo')),
            ],
        ),
    ]
