# Generated by Django 4.1.4 on 2024-06-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0047_detailsppb_detailbahan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemusnahanbahanbaku',
            name='Jumlah',
            field=models.FloatField(),
        ),
    ]
