# Generated by Django 4.1.4 on 2024-09-24 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0048_suratjalanpembelian_alter_produk_tanggalpembuatan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='bahanbakusubkon',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='display',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='produksubkon',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 24, 8, 28, 33, 549080)),
        ),
        migrations.DeleteModel(
            name='DetailSuratJalanPembelian',
        ),
        migrations.DeleteModel(
            name='SuratJalanPembelian',
        ),
    ]
