# Generated by Django 4.1.4 on 2024-06-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0049_remove_transaksiproduksi_detailsppbdisplay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratjalanpembelian',
            name='NoInvoice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suratjalanpembelian',
            name='TanggalInvoice',
            field=models.DateField(blank=True, null=True),
        ),
    ]
