# Generated by Django 4.1.4 on 2024-09-27 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0050_suratjalanpembelian_artikel_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 27, 22, 42, 54, 887677)),
        ),
        migrations.CreateModel(
            name='TransaksiProduksiProdukSubko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('Jumlah', models.FloatField()),
                ('Keterangan', models.CharField(max_length=255)),
                ('KodeProduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abadi.produksubkon')),
            ],
        ),
    ]
