# Generated by Django 4.1.4 on 2024-06-25 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0050_suratjalanpembelian_noinvoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksiproduksi',
            name='KodeArtikel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.artikel'),
        ),
        migrations.AlterField(
            model_name='transaksiproduksi',
            name='KodeDisplay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.display'),
        ),
    ]
