# Generated by Django 4.1.4 on 2024-06-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0051_alter_transaksiproduksi_kodeartikel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsuratjalanpenerimaanproduksubkon',
            name='Harga',
            field=models.FloatField(default=0),
        ),
    ]
