# Generated by Django 4.1.4 on 2024-09-28 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0052_rename_transaksiproduksiproduksubko_transaksiproduksiproduksubkon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 9, 28, 11, 45, 59, 622852)),
        ),
    ]
