# Generated by Django 4.1.4 on 2024-06-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0052_detailsuratjalanpenerimaanproduksubkon_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsuratjalanpenerimaanproduksubkon',
            name='NoInvoice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detailsuratjalanpenerimaanproduksubkon',
            name='TanggalInvoice',
            field=models.DateField(blank=True, null=True),
        ),
    ]
