# Generated by Django 4.1.4 on 2024-10-05 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0053_alter_produk_tanggalpembuatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='Supplier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 10, 5, 18, 32, 32, 15550)),
        ),
    ]
