# Generated by Django 4.1.4 on 2024-12-15 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0054_purchaseorder_supplier_alter_produk_tanggalpembuatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 12, 54, 59, 934028)),
        ),
    ]
