# Generated by Django 4.1.4 on 2024-06-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0054_remove_detailsuratjalanpenerimaanproduksubkon_noinvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratjalanpenerimaanproduksubkon',
            name='NoInvoice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='suratjalanpenerimaanproduksubkon',
            name='TanggalInvoice',
            field=models.DateField(blank=True, null=True),
        ),
    ]
