# Generated by Django 4.1.4 on 2024-07-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0055_suratjalanpenerimaanproduksubkon_noinvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsuratjalanpembelian',
            name='HargaDollar',
            field=models.FloatField(default=0),
        ),
    ]
