# Generated by Django 4.1.4 on 2024-12-15 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0056_alter_produk_tanggalpembuatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksigudang',
            name='TransaksiRetur',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 13, 16, 46, 948401)),
        ),
    ]
