# Generated by Django 4.1.4 on 2024-07-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0056_detailsuratjalanpembelian_hargadollar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penyesuaian',
            name='KodePenyusun',
        ),
        migrations.AddField(
            model_name='penyesuaian',
            name='KodeProduk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.produk'),
        ),
    ]
