# Generated by Django 4.1.4 on 2024-07-01 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0057_remove_penyesuaian_kodepenyusun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyesuaian',
            name='KodeArtikel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abadi.artikel'),
        ),
    ]
