# Generated by Django 4.1.4 on 2024-07-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0058_penyesuaian_kodeartikel'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsuratjalanpenerimaanproduksubkon',
            name='KeteranganACC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suratjalanpenerimaanproduksubkon',
            name='Supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
