# Generated by Django 4.1.4 on 2024-07-09 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0059_detailsuratjalanpenerimaanproduksubkon_keteranganacc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailsuratjalanpenerimaanproduksubkon',
            old_name='IDDetailSJPengirimanSubkon',
            new_name='IDDetailSJPenerimaanSubkon',
        ),
    ]
