# Generated by Django 4.1.4 on 2024-07-16 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0060_rename_iddetailsjpengirimansubkon_detailsuratjalanpenerimaanproduksubkon_iddetailsjpenerimaansubkon'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyesuaian',
            name='lokasi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abadi.lokasi'),
        ),
    ]
