# Generated by Django 4.1.4 on 2024-07-17 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abadi', '0061_penyesuaian_lokasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='TanggalPembuatan',
            field=models.DateField(default=datetime.datetime(2024, 7, 17, 11, 42, 11, 690479)),
        ),
    ]
